### ISSUE TITLE
Close to tray

### ISSUE THREAD

**Issue by Ashark** [AlynxZhou/showmethekey#14]
Hi, thanks for the project!
Unfortunately, it currently has not yet similar possibilities with screenkey.
Would you like to add close to tray function? So the app window will not be shown in the taskbar.

**Comment by AlynxZhou** [comment]
No, because I use GNOME and GNOME does not have a tray 😸.

Seriously, "Close to Tray" is something really strange to me, I mean when you click "Close", you do not want really "Close", but "Minimize to Tray and Keep Running"? I just dislike this, when I click "Close" I just really want to close it.

If you don't use it, I suggest to put it aside, or put it into another workspace. Being a screenkey alternative does not mean behaving the same as it. I'm sorry but I really dislike tray icon.

**Comment by Ashark** [comment]
No no no, close to tray is a must for some applications. These applications are meant to be working in background. Take for example obs. When you record some lesson, you do not want obs window to be in your taskbar, or even on another desktop. But still you want to see its status (recording or not icon in tray) and quick access to start/stop recording.
I understand that gnome has different concept. And not having tray is a miss as I consider it.
But anyway, thanks for the project. I hope maybe kdocker could support wayland and kde users could workaround this problem or qt analog appear.
