### ISSUE TITLE
[Feature] Show direction in which the mouse cursor is moving

### ISSUE THREAD

**Issue by Zeioth** [AlynxZhou/showmethekey#15]
Example: https://www.youtube.com/watch?v=F1bazIjJ2xw

**Comment by AlynxZhou** [comment]
I think I replied this, but I didn't, so I reply now.

I don't think this is necessary, if you are streaming or recording with it, you probably already record your cursor, this program is for the problem that watchers cannot see your modifier keys.

And your example, it's a gaming video, AFAIK most gaming streamers use OBS plugin for it, and I think the video also uses OBS plugin. If you want to use this program for gaming, I suggest not. When you play games you want best performance and then game takes full screen, prevents compositor redirect, so no window can be above your game, and this program just cannot show, it's a floating window, requests compositor redirect.

That's why you should use OBS plugins for game, they are running inside OBS Studio, directly into your video stream, not your desktop compositor.
