### ISSUE TITLE
Install ShowMeTheKey for linx-ubuntu

### ISSUE THREAD

**Issue by pritam12426** [AlynxZhou/showmethekey#20]
#### I try this command

`bash
apt install showmethekey
`

**Comment by abrac** [comment]
On Ubuntu, you have to install it form source, using the instructions found in [README.md](https://github.com/AlynxZhou/showmethekey#build-from-source)

If you are using Ubuntu 22.04 (the current LTS version), you will need to install ShowMeTheKey version **1.6.3**, since newer versions use GTK4, which is not available in Ubuntu 22.04 repositories. 

Here is a link to [ShowMeTheKey v1.6.3](https://github.com/AlynxZhou/showmethekey/releases/tag/v1.6.3).

**Comment by AlynxZhou** [comment]
Closed because there is already a kind guy providing solution.
