### ISSUE TITLE
Mapped key shown wrong.

### ISSUE THREAD

**Issue by NewsonUpreti** [AlynxZhou/showmethekey#35]
I have mapped caps lock as my esc key and shift + caps lock as normal caps lock.
*  When I press capslock which is esc, shows caps lock instead of esc.
*  When I press letters after pressing caps lock which is escape.    Instead of default state It shows letters in capital, and shows small again if I press caps lock which is actually esc in my computer. 
*  Its okay if it shows caps lock instead of esc, But when I type letters, it shows capital and small letters in its windows even when I have not turned on caps lock yet with shift + caps lock.  I work at neovim and its crucial to get accurate keys and this didn't help. I am using fedora 39 with gnome, wayland. 
* Still its an awesome tool but Didn't help me, Hope it gets fixed so I can use again. 
* Dev can try by mapping caps lock as esc once and check what I just said.

Thanks

**Comment by AlynxZhou** [comment]
Hmm I forget to reply this.

If you are remapping your keys via X11, or compositor, it is not supported by this app, because it skips X11 or compositor and read directly from libinput. So if you need to remap keys, I suggest to do it via udev, I personally swapped Caps Locks and Ctrl, it works fine, there is another benefit for it: udev remapping will also work under TTY.

This webpage will be helpful if you want to do the same with me: https://wiki.archlinux.org/title/Map_scancodes_to_keycodes

However if you are using some more complex setup (for example, short press Cap Locks for Cap Locks and long press Cap Locks for Ctrl, AFAIK this requires some running daemon to handle it and not widely supported by Wayland compositors), it cannot be supported, sorry.

**Comment by AlynxZhou** [comment]
Maybe I should add a section in README because I think this is not the first time people asking this and I always give the same reply.

**Comment by NewsonUpreti** [comment]
I tried using with X11 as well, Didn't work. I have remapped the keys with this: set xkbmap -option "caps:escape_shifted_capslock" . This app is working great, This is the only problem and Its not a huge problem for me . Thanks for replying.

**Comment by AlynxZhou** [comment]
> I tried using with X11 as well, Didn't work. I have remapped the keys with this: set xkbmap -option "caps:escape_shifted_capslock" .

It is expected not to work with xkbmap, Xserver is something at the same level with Wayland compositor, and libinput is at lower layer.
